// This file is auto-generated by @repo/crpc.
// Do not edit manually. Managed internally by @repo/crpc.

import { createBuilder, createCrud, operations, to } from "@repo/crpc";
import { createAdapterFactory } from "better-auth/adapters";
import type { GenericActionCtx, GenericDataModel } from "convex/server";
import { v } from "convex/values";

type ActionCtx<DataModel extends GenericDataModel = GenericDataModel> = GenericActionCtx<DataModel>;

const whereClauseSchema = v.object({
  connector: v.optional(v.union(v.literal("AND"), v.literal("OR"))),
  field: v.string(),
  operator: v.optional(
    v.union(
      v.literal("contains"),
      v.literal("ends_with"),
      v.literal("eq"),
      v.literal("gt"),
      v.literal("gte"),
      v.literal("in"),
      v.literal("lt"),
      v.literal("lte"),
      v.literal("ne"),
      v.literal("not_in"),
      v.literal("starts_with"),
    ),
  ),
  value: v.any(),
});

const querySchema = v.object({
  limit: v.optional(v.number()),
  model: v.string(),
  offset: v.optional(v.number()),
  op: v.union(v.literal("findOne"), v.literal("findMany"), v.literal("count")),
  select: v.optional(v.array(v.string())),
  sortBy: v.optional(
    v.object({
      direction: v.union(v.literal("asc"), v.literal("desc")),
      field: v.string(),
    }),
  ),
  where: v.optional(v.array(whereClauseSchema)),
});

const mutationSchema = v.object({
  input: v.any(),
  op: v.union(
    v.literal("create"),
    v.literal("updateOne"),
    v.literal("updateMany"),
    v.literal("deleteOne"),
    v.literal("deleteMany"),
  ),
  select: v.optional(v.array(v.string())),
});

function createQueryHandler<DataModel extends GenericDataModel = GenericDataModel>(
  crud: ReturnType<typeof createCrud<DataModel>>,
) {
  return async (ctx: any, args: any) => {
    if (args.op === "findOne") {
      return crud.findOne(ctx, {
        select: args.select,
        table: args.model,
        where: args.where,
      });
    }

    if (args.op === "findMany") {
      return crud.findMany(ctx, {
        limit: args.limit,
        offset: args.offset,
        select: args.select,
        sortBy: args.sortBy,
        table: args.model,
        where: args.where,
      });
    }

    return crud.count(ctx, {
      table: args.model,
      where: args.where,
    });
  };
}

function createMutationHandler<DataModel extends GenericDataModel = GenericDataModel>(
  crud: ReturnType<typeof createCrud<DataModel>>,
) {
  return async (ctx: any, args: any) => {
    if (args.op === "create") {
      return crud.create(ctx, {
        data: args.input.data,
        select: args.select,
        table: args.input.model,
      });
    }

    if (args.op === "updateOne") {
      return crud.updateOne(ctx, {
        select: args.select,
        table: args.input.model,
        update: args.input.update,
        where: args.input.where,
      });
    }

    if (args.op === "updateMany") {
      return crud.updateMany(ctx, {
        table: args.input.model,
        update: args.input.update,
        where: args.input.where,
      });
    }

    if (args.op === "deleteOne") {
      return crud.deleteOne(ctx, {
        table: args.input.model,
        where: args.input.where,
      });
    }

    return crud.deleteMany(ctx, {
      table: args.input.model,
      where: args.where,
    });
  };
}

function createAdapter<DataModel extends GenericDataModel>(ctx: ActionCtx<DataModel>) {
  const crud = createCrud<DataModel>();
  const convex = createBuilder<DataModel>();

  const query = convex.query().input(querySchema).handler(createQueryHandler(crud));
  const mutate = convex.mutation().input(mutationSchema).handler(createMutationHandler(crud));

  const adapter = createAdapterFactory({
    adapter: () => ({
      count: async (input) =>
        (await query(to("query", ctx), {
          ...input,
          op: "count",
        })) as number,
      create: async <T extends Record<string, any>>({
        select,
        ...input
      }: {
        model: string;
        data: T;
        select?: string[];
      }) =>
        (await mutate(to("mutation", ctx), {
          input,
          op: "create",
          select,
        })) as T,
      delete: async (input: any): Promise<void> => {
        await mutate(to("mutation", ctx), {
          input,
          op: "deleteOne",
        });
      },
      deleteMany: async (input: any): Promise<number> => {
        const deleted = (await mutate(to("mutation", ctx), {
          input,
          op: "deleteMany",
        })) as { count: number };
        return deleted.count;
      },
      findMany: async <T>(input: any): Promise<T[]> =>
        (await query(to("query", ctx), {
          ...input,
          op: "findMany",
        })) as T[],
      findOne: async <T>(input: any): Promise<T | null> =>
        (await query(to("query", ctx), {
          ...input,
          op: "findOne",
        })) as T | null,
      update: async <T>(input: {
        model: string;
        where: any;
        update: any;
        select?: string[];
      }): Promise<T | null> =>
        (await mutate(to("mutation", ctx), {
          input,
          op: "updateOne",
        })) as T | null,
      updateMany: async (input: { model: string; where: any; update: any }): Promise<number> => {
        const updated = (await mutate(to("mutation", ctx), {
          input,
          op: "updateMany",
        })) as { count: number };
        return updated.count;
      },
    }),
    config: {
      adapterId: "Convex Adapter",
      supportsJSON: true,
      supportsNumericIds: false,
      usePlural: true,
    },
  });

  return adapter;
}

export { createAdapter, mutationSchema, operations, querySchema };
