// This file is auto-generated by @repo/crpc.
// Do not edit manually. Managed internally by @repo/crpc.

import { httpMiddleware as baseHttpMiddleware } from "@repo/better-auth/http";

import { getAuth } from "./auth";

function httpMiddleware() {
  return baseHttpMiddleware({ getAuth });
}

export { httpMiddleware };
