// @ts-nocheck
// biome-ignore-all lint: codegen
// This file is auto-generated by @repo/crpc.
// Do not edit manually. Managed internally by @repo/crpc.

import { betterAuth } from "better-auth";
import { createAdapterFactory } from "better-auth/adapters";
import type { GenericSchema, SchemaDefinition } from "convex/server";
import { v } from "convex/values";
import { createAdapter as createAuthCrud } from "../../../crpc/src/auth/db/adapter";
import type {
	GenericCtx as BaseGenericCtx,
	MutationCtx as BaseMutationCtx,
	ActionCtx as RuntimeActionCtx,
} from "../../../crpc/src/server/builder/types";
import {
	type BetterAuthOptionsWithoutDatabase,
	defineAuth as baseDefineAuth,
	type GenericAuthDefinition,
	type GenericAuthTriggers,
} from "@repo/better-auth/server";
import { defineTriggers as baseDefineTriggers } from "../../../crpc/src/server/define-triggers";
import { createBuilder } from "@repo/crpc/server";
import { internal } from "../_generated/api";
import type { DataModel } from "../_generated/dataModel";
import {
	internalAction,
	internalMutation,
	internalQuery,
} from "../_generated/server";
import authDefinition from "../auth";

type ActionCtx = RuntimeActionCtx<DataModel>;
type GenericCtx = BaseGenericCtx<DataModel>;
type MutationCtx = BaseMutationCtx<DataModel>;

type ProcessLike = Record<string, RuntimeEnv | undefined> | undefined;
type RuntimeEnv = Record<string, string | undefined>;
type GlobalLike = Record<string, unknown>;

type ConvexPluginWithEndpoints = {
	endpoints: Record<string, (args: unknown) => Promise<unknown>> & {
		getLatestJwks: (args: unknown) => Promise<unknown>;
		rotateKeys: (args: unknown) => Promise<unknown>;
	};
	id: string;
};

function catchEnv(key: string) {
	const processKey = "pro" + "cess";
	const envKey = "e" + "nv";

	const globalObject = globalThis as GlobalLike;
	const processObject = globalObject[processKey] as ProcessLike;
	const envObject = processObject?.[envKey];

	return envObject?.[key];
}

const getConvexPlugin = (ctx: ActionCtx) => {
	const authOptions = authDefinition(ctx);

	const convexPlugin = authOptions.plugins!.find(
		(p) =>
			typeof p === "object" &&
			p !== null &&
			(p as { id?: string }).id === "convex",
	) as ConvexPluginWithEndpoints;

	return {
		authOptions,
		convexPlugin,
	};
};

const authCrud = createAuthCrud<
	DataModel,
	SchemaDefinition<GenericSchema, true>,
	MutationCtx
>({
	getTriggers: (ctx) => authDefinition(ctx).triggers,
});

const createAdapter = (ctx: RuntimeActionCtx<DataModel>) => {
	const adapterCreator = createAdapterFactory({
		adapter: () => {
			const runQuery = (args: Record<string, unknown>) =>
				ctx.runQuery(internal.crpc.auth.queryAdapter, args);

			const runMutation = (args: Record<string, unknown>) =>
				ctx.runMutation(internal.crpc.auth.mutationAdapter, args);

			return {
				count: async ({ model, where }) => {
					const results = await runQuery({
						model,
						op: "findMany",
						where,
					});

					return (results as unknown[]).length;
				},
				create: async ({ data, model, select }) =>
					runMutation({
						input: { data, model },
						op: "create",
						select,
					}),
				delete: async ({ model, where }) =>
					runMutation({
						input: { model, where },
						op: "deleteOne",
					}),
				deleteMany: async ({ model, where }) => {
					const result = (await runMutation({
						input: { model, where },
						op: "deleteMany",
					})) as { count: number };

					return result.count;
				},
				findMany: async (args) =>
					runQuery({
						...args,
						op: "findMany",
					}),
				findOne: async (args) =>
					runQuery({
						...args,
						op: "findOne",
					}),
				update: async ({ model, update, where }) =>
					runMutation({
						input: { model, update, where },
						op: "updateOne",
					}),
				updateMany: async ({ model, update, where }) => {
					const result = (await runMutation({
						input: { model, update, where },
						op: "updateMany",
					})) as { count: number };

					return result.count;
				},
			};
		},
		config: {
			adapterId: "convex",
			adapterName: "Convex Adapter",
			supportsArrays: false,
			supportsBooleans: true,
			supportsDates: true,
			supportsJSON: true,
			supportsNumericIds: false,
			transaction: false,
			usePlural: false,
		},
	});

	return adapterCreator;
};

export function getAuth(ctx: RuntimeActionCtx<DataModel>) {
	const authOptions = authDefinition(ctx);
	return betterAuth({
		...authOptions,
		database: createAdapter(ctx),
	});
}

export type Auth = ReturnType<typeof getAuth>;

export function getHandler(ctx: RuntimeActionCtx<DataModel>) {
	const auth = getAuth(ctx);
	return { handler: auth.handler.bind(auth) };
}

export async function runEndpoint(
	ctx: RuntimeActionCtx<DataModel>,
	endpointName: "getLatestJwks" | "rotateKeys",
) {
	const { authOptions, convexPlugin } = getConvexPlugin(ctx);
	const endpoint = convexPlugin.endpoints[endpointName];
	const secret = catchEnv("BETTER_AUTH_SECRET");

	return await endpoint({
		context: {
			adapter: createAdapter(ctx),
			baseURL: authOptions.baseURL,
			logger: console,
			options: {
				baseURL: authOptions.baseURL,
				plugins: [convexPlugin],
			},
			secret,
			secretConfig: secret,
		},
		headers: new Headers(),
		method: "POST",
		path: endpoint.path,
		returnHeaders: false,
		returnStatus: false,
	});
}

export function defineAuth<
	AuthOptions extends
		BetterAuthOptionsWithoutDatabase = BetterAuthOptionsWithoutDatabase,
>(
	definition: GenericAuthDefinition<
		ActionCtx,
		DataModel,
		SchemaDefinition<GenericSchema, true>,
		AuthOptions,
		MutationCtx
	>,
) {
	return baseDefineAuth<
		ActionCtx,
		DataModel,
		SchemaDefinition<GenericSchema, true>,
		AuthOptions,
		MutationCtx
	>(definition);
}

export function defineTriggers<
	Schema extends SchemaDefinition<GenericSchema, true>,
>(
	schema: Schema,
	triggers: GenericAuthTriggers<DataModel, Schema, MutationCtx>,
) {
	return baseDefineTriggers<Schema, DataModel, MutationCtx>(schema, triggers);
}

const convex = createBuilder<DataModel>();

export const queryAdapter = convex
	.query()
	.input(
		v.object({
			limit: v.optional(v.number()),
			model: v.string(),
			offset: v.optional(v.number()),
			op: v.union(v.literal("findOne"), v.literal("findMany")),
			select: v.optional(v.array(v.string())),
			sortBy: v.optional(v.any()),
			where: v.optional(v.any()),
		}),
	)
	.handler(async (ctx, args) => {
		if (args.op === "findOne") {
			return await authCrud.findOne(ctx, {
				model: args.model,
				select: args.select,
				where: args.where,
			});
		}

		return await authCrud.findMany(ctx, {
			limit: args.limit,
			model: args.model,
			offset: args.offset,
			sortBy: args.sortBy,
			where: args.where,
		});
	})
	.internal();

export const mutationAdapter = convex
	.mutation()
	.input(
		v.object({
			input: v.any(),
			op: v.union(
				v.literal("create"),
				v.literal("updateOne"),
				v.literal("updateMany"),
				v.literal("deleteOne"),
				v.literal("deleteMany"),
			),
			select: v.optional(v.array(v.string())),
		}),
	)
	.handler(async (ctx, args) => {
		switch (args.op) {
			case "create":
				return await authCrud.create(ctx, {
					data: args.input.data,
					model: args.input.model,
					select: args.select,
				});
			case "updateOne":
				return await authCrud.updateOne(ctx, {
					model: args.input.model,
					update: args.input.update,
					where: args.input.where,
				});
			case "updateMany":
				return await authCrud.updateMany(ctx, {
					model: args.input.model,
					update: args.input.update,
					where: args.input.where,
				});
			case "deleteOne":
				return await authCrud.deleteOne(ctx, {
					model: args.input.model,
					where: args.input.where,
				});
			case "deleteMany":
				return await authCrud.deleteMany(ctx, {
					model: args.input.model,
					where: args.input.where,
				});
		}
	})
	.internal();

export const getLatestJwk = internalAction({
	args: {},
	handler: (ctx) => runEndpoint(ctx, "getLatestJwks"),
});

export const rotateKeys = internalAction({
	args: {},
	handler: (ctx) => runEndpoint(ctx, "rotateKeys"),
});

