// This file is auto-generated by @repo/crpc.
// Do not edit manually. Managed internally by @repo/crpc.

import type { MiddlewareOptions } from "@repo/crpc/auth/http";
import { betterAuth } from "@repo/crpc/auth/http";

import { getHandler } from "./auth";

function middleware(options: Omit<MiddlewareOptions, "getAuth">) {
  return betterAuth({
    ...options,
    getAuth: getHandler,
  });
}

export { middleware };
