import { z } from "zod";
import {
  PUBLIC_CONVEX_SITE_URL,
  PUBLIC_CONVEX_URL,
  PUBLIC_DASHBOARD_URL,
  PUBLIC_MARKETING_URL,
  PUBLIC_POSTHOG_API_KEY,
  PUBLIC_POSTHOG_HOST,
} from "$env/static/public";

const envSchema = z.object({
  PUBLIC_CONVEX_SITE_URL: z.url(),
  PUBLIC_CONVEX_URL: z.url(),
  PUBLIC_DASHBOARD_URL: z.url(),
  PUBLIC_MARKETING_URL: z.url(),
  PUBLIC_POSTHOG_API_KEY: z.string(),
  PUBLIC_POSTHOG_HOST: z.url(),
});

export const env = envSchema.parse({
  PUBLIC_CONVEX_SITE_URL,
  PUBLIC_CONVEX_URL,
  PUBLIC_DASHBOARD_URL,
  PUBLIC_MARKETING_URL,
  PUBLIC_POSTHOG_API_KEY,
  PUBLIC_POSTHOG_HOST,
});
