import { spawn } from "node:child_process";
import { watch as fsWatch, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { syncEnv } from "./sync";

const __dirname = dirname(fileURLToPath(import.meta.url));

const TEMPLATES = resolve(__dirname, "generated");

const REGEN_DEBOUNCE_MS = 100;

/**
 * The files that are generated by the Convex builder.
 */
const GENERATED_STEMS = new Set([
	"api.d.ts",
	"api.js",
	"dataModel.d.ts",
	"server.d.ts",
	"server.js",
]);

function readTemplate(name: string): string {
	return readFileSync(resolve(TEMPLATES, name), "utf-8");
}

async function runConvex(
	args: string[],
	cwd = process.cwd(),
	env?: Record<string, string>,
): Promise<number> {
	return new Promise((ok, err) => {
		const child = spawn("bunx", ["convex", ...args], {
			cwd,
			env: env ? { ...process.env, ...env } : process.env,
			stdio: "inherit",
		});

		child.on("error", (e) => {
			err(e);
		});

		child.on("exit", (code) => {
			if (code === 0) {
				ok(0);
			} else {
				err(new Error(`convex ${args.join(" ")} failed`));
			}
		});
	});
}

async function convexPipe(
	args: string[],
	cwd: string,
): Promise<string | undefined> {
	return new Promise((ok) => {
		const child = spawn("bunx", ["convex", ...args], {
			cwd,
			stdio: ["ignore", "pipe", "ignore"],
		});

		let out = "";

		child.stdout?.on("data", (c) => {
			out += c.toString();
		});

		child.on("error", () => ok(undefined));

		child.on("exit", (code) => ok(code === 0 ? out.trim() : undefined));
	});
}

const CRPC_DIR = "crpc";

/**
 * Checks if the JWKS environment variable is set and sets it if it’s not.
 */
async function checkOrSetJwks(cwd: string, prod: boolean): Promise<void> {
	const args = prod ? ["--prod"] : [];
	if ((await convexPipe(["env", "get", "JWKS", ...args], cwd)) !== undefined) {
		return;
	}
	const jwks = await convexPipe(
		["run", `${CRPC_DIR}/auth:getLatestJwk`, ...args],
		cwd,
	);
	if (jwks) {
		await runConvex(["env", "set", "JWKS", jwks, ...args], cwd);
	}
}

async function generateFiles(cwd: string): Promise<void> {
	const out = resolve(cwd, "src", CRPC_DIR);
	await mkdir(out, { recursive: true });

	const writes = [
		["auth.ts", readTemplate("auth.ts")],
		["http.ts", readTemplate("http.ts")],
		["types.ts", readTemplate("types.ts")],
	] as const;

	await Promise.all(
		writes.map(([name, content]) => writeFile(resolve(out, name), content)),
	);
}

/**
 * Watches for Convex build changes and regenerates the files.
 */
function createConvexWatcher(cwd: string) {
	const targetDir = resolve(cwd, "src/_generated");

	let timer: ReturnType<typeof setTimeout> | undefined;
	let taskQueue = Promise.resolve();

	const scheduleGeneration = () => {
		taskQueue = taskQueue.then(() => generateFiles(cwd));
	};

	/**
	 * Responsible for listening and reacting to changes in the target directory.
	 */
	const fsListener = (_: string, filename: string | Buffer | null) => {
		if (!filename) {
			return;
		}

		/**
		 * A stem is a file name without the path.
		 */
		const stem = filename.toString().replaceAll("\\", "/").split("/").pop();

		if (!(stem && GENERATED_STEMS.has(stem))) {
			return;
		}

		if (timer) {
			clearTimeout(timer);
		}

		timer = setTimeout(scheduleGeneration, REGEN_DEBOUNCE_MS);
	};

	const fsWatcher = fsWatch(
		targetDir,
		{
			/**
			 * To be able to watch the generated directory.
			 */
			recursive: true,
		},
		fsListener,
	);

	return {
		/**
		 * Flushes the task queue.
		 * @remark Avoids race conditions.
		 */
		async flush() {
			if (timer) {
				clearTimeout(timer);
				timer = undefined;
			}

			scheduleGeneration();
			await taskQueue;
		},
		/**
		 * Closes the filesystem watcher.
		 */
		stop() {
			if (timer) {
				clearTimeout(timer);
			}

			fsWatcher.close();
		},
	};
}

async function runCodegen(cwd: string, prod: boolean): Promise<void> {
	await checkOrSetJwks(cwd, prod);
	await generateFiles(cwd);

	const watcher = createConvexWatcher(cwd);

	// Nesting try/catch is a bit weird.
	try {
		const args = prod ? ["--prod"] : [];
		try {
			await runConvex(["codegen", ...args], cwd, { CRPC_CODEGEN: "1" });
		} catch {
			await generateFiles(cwd);
			await runConvex(["codegen", ...args], cwd, { CRPC_CODEGEN: "1" });
		}
		await watcher.flush();
	} finally {
		watcher.stop();
	}
}

async function build() {
	await runCodegen(process.cwd(), false);
}

async function watch() {
	const cwd = process.cwd();
	await runCodegen(cwd, false);
	const watcher = createConvexWatcher(cwd);

	try {
		await runConvex(["dev"], cwd, { CRPC_CODEGEN: "1" });
	} finally {
		watcher.stop();
	}
}

async function deploy(args: string[] = []): Promise<void> {
	const cwd = process.cwd();
	const prod = args.includes("--prod");

	await runCodegen(cwd, prod);

	await runConvex(["deploy", ...args], cwd, {
		/**
		 * Sentinel value to indicate that the codegen is present.
		 */
		CRPC_CODEGEN: "1",
	});
}

interface SyncOptions {
	/**
	 * Makes sure those are set in the development environment.
	 */
	auth?: boolean;
	/**
	 * Rotates the keys in the production environment.
	 */
	force?: boolean;
	/**
	 * Makes sure those are set in the production environment.
	 */
	prod?: boolean;
}

async function sync(opts: SyncOptions) {
	await syncEnv(opts);
}

export { build, deploy, runConvex, sync, watch };
