// This file is auto-generated by @repo/crpc.
// Do not edit manually. Managed internally by @repo/crpc.

import {
  httpMiddleware as baseHttpMiddleware,
  type MiddlewareOptions,
} from "@repo/better-auth/http";

import { getAuth } from "./auth";

function httpMiddleware(opts: MiddlewareOptions) {
  return baseHttpMiddleware({ ...opts, getAuth });
}

export { httpMiddleware };
