// This file is auto-generated by @repo/crpc.
// Do not edit manually. Managed internally by @repo/crpc.

import { BetterAuthOptions } from "better-auth/types";
import {
  GenericActionCtx,
  GenericDataModel,
  GenericMutationCtx,
  DocumentByName,
  GenericQueryCtx,
  SchemaDefinition,
  GenericSchema,
} from "convex/server";

type MaybePromise<T> = T | Promise<T>;

type Simplify<T> = { [K in keyof T]: T[K] } & {};

type DateifyAtFields<TDoc extends Record<string, unknown>> = Simplify<{
  [K in keyof TDoc]: K extends `${string}At` ? (TDoc[K] extends number ? Date : TDoc[K]) : TDoc[K];
}>;

type RemoveSystemFields<TDoc extends Record<string, unknown>> = Simplify<{
  [K in keyof TDoc as K extends "_id" | "_creationTime" ? never : K]: TDoc[K];
}>;

type RawTableDoc<DataModel extends GenericDataModel, TableName extends string> = DocumentByName<
  DataModel,
  TableName
>;

type AuthTriggerDoc<DataModel extends GenericDataModel, TableName extends string> = Simplify<
  RemoveSystemFields<RawTableDoc<DataModel, TableName>> &
    (RawTableDoc<DataModel, TableName> extends { _id: infer TId }
      ? { id: TId }
      : Record<never, never>)
>;

type AuthTriggerInsertData<
  DataModel extends GenericDataModel,
  TableName extends string,
> = DateifyAtFields<RemoveSystemFields<RawTableDoc<DataModel, TableName>>>;

type AuthTriggerUpdateData<DataModel extends GenericDataModel, TableName extends string> = Partial<
  AuthTriggerInsertData<DataModel, TableName>
>;

type TriggerChangeId<TDoc> = TDoc extends { _id: infer TId }
  ? TId
  : TDoc extends { id: infer TId }
    ? TId
    : unknown;

type GenericAuthTriggerChange<
  TDoc extends Record<string, unknown> = Record<string, unknown>,
  TId = TriggerChangeId<TDoc>,
> =
  | {
      id: TId;
      newDoc: TDoc;
      oldDoc: null;
      operation: "insert";
    }
  | {
      id: TId;
      newDoc: TDoc;
      oldDoc: TDoc;
      operation: "update";
    }
  | {
      id: TId;
      newDoc: null;
      oldDoc: TDoc;
      operation: "delete";
    };

type GenericAuthBeforeResult<TData extends Record<string, unknown>> =
  | void
  | false
  | {
      data: Partial<TData>;
    };

interface GenericAuthTriggerHandlers<
  DataModel extends GenericDataModel,
  TableName extends string,
  MutationCtx,
> {
  change?: (
    change: GenericAuthTriggerChange<AuthTriggerDoc<DataModel, TableName>>,
    ctx: MutationCtx,
  ) => MaybePromise<void>;
  create?: {
    after?: (doc: AuthTriggerDoc<DataModel, TableName>, ctx: MutationCtx) => MaybePromise<void>;
    before?: (
      data: AuthTriggerInsertData<DataModel, TableName>,
      ctx: MutationCtx,
    ) => MaybePromise<GenericAuthBeforeResult<AuthTriggerInsertData<DataModel, TableName>>>;
  };
  delete?: {
    after?: (doc: AuthTriggerDoc<DataModel, TableName>, ctx: MutationCtx) => MaybePromise<void>;
    before?: (
      doc: AuthTriggerDoc<DataModel, TableName>,
      ctx: MutationCtx,
    ) => MaybePromise<GenericAuthBeforeResult<AuthTriggerDoc<DataModel, TableName>>>;
  };
  update?: {
    after?: (newDoc: AuthTriggerDoc<DataModel, TableName>, ctx: MutationCtx) => MaybePromise<void>;
    before?: (
      update: AuthTriggerUpdateData<DataModel, TableName>,
      ctx: MutationCtx,
    ) => MaybePromise<GenericAuthBeforeResult<AuthTriggerUpdateData<DataModel, TableName>>>;
  };
}

type GenericAuthTriggers<
  DataModel extends GenericDataModel,
  Schema extends SchemaDefinition<GenericSchema, true>,
  MutationCtx = unknown,
> = {
  [K in keyof Schema["tables"] & string]?: GenericAuthTriggerHandlers<DataModel, K, MutationCtx>;
};

type ActionCtx<DataModel extends GenericDataModel = GenericDataModel> = GenericActionCtx<DataModel>;
type QueryCtx<DataModel extends GenericDataModel = GenericDataModel> = GenericQueryCtx<DataModel>;
type MutationCtx<DataModel extends GenericDataModel = GenericDataModel> =
  GenericMutationCtx<DataModel>;

type DataModel<T extends GenericDataModel = GenericDataModel> = T;

type GenericAuthDefinition<
  GenericCtx = unknown,
  DataModel extends GenericDataModel = GenericDataModel,
  Schema extends SchemaDefinition<GenericSchema, true> = SchemaDefinition<GenericSchema, true>,
  AuthOptions extends BetterAuthOptions = BetterAuthOptions,
  MutationCtx = GenericCtx,
> = (ctx: GenericCtx) => AuthOptions & {
  triggers?: GenericAuthTriggers<DataModel, Schema, MutationCtx>;
};

export { ActionCtx, MutationCtx, QueryCtx, DataModel, GenericAuthDefinition, GenericAuthTriggers };
